-- AlterTable
ALTER TABLE "Comments" ADD COLUMN     "bad" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "like" INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "Posts" ADD COLUMN     "like" INTEGER NOT NULL DEFAULT 0;
